export const NAV_LINKS = [
  { label: 'Work', href: '/work' },
  { label: 'Services', href: '/services' },
  { label: 'About', href: '/about' },
  { label: 'Insights', href: '/insights' },
];

export const SERVICES = [
  // Tier 1 — Quick Wins
  {
    tier: 1,
    tierLabel: 'TIER 01 — QUICK WINS',
    tierHeadline: 'See results within weeks, not months.',
    tierDescription: "We don't offer 'web design.' We offer specific, priced, scoped engagements — each designed to solve a defined problem and produce a measurable result. No open-ended retainers that drain your budget. No vague deliverables.",
    slug: 'conversion-audit',
    name: 'Conversion Audit + Fix Sprint',
    outcome: 'Find exactly where you\'re losing money — and fix it.',
    price: '$3,000–5,000',
    timeline: 'Results in 2–3 weeks',
    heroSubtitle: 'We don\'t guess where the leaks are. We use data to find every friction point costing you revenue — then we fix them, fast.',
    description: 'Most businesses have traffic. Most businesses are bleeding money at the conversion layer. Your analytics dashboard shows visitors, but it doesn\'t show you why they\'re leaving. Our Conversion Audit goes beyond surface-level metrics. We use behavioral analysis, heatmaps, session recordings, and funnel modeling to pinpoint exactly where your revenue is leaking — and then we fix it within weeks, not months.',
    features: [
      'Full-funnel behavioral analysis',
      'Heatmap & session recording review',
      'Competitor conversion benchmarking',
      'Prioritized fix implementation',
      'A/B testing setup for critical pages',
      'Post-fix performance report with metrics'
    ],
    results: [
      { metric: '+288%', label: 'Average revenue increase' },
      { metric: '2 weeks', label: 'Average time to first results' },
      { metric: '94%', label: 'Client retention rate' },
    ],
    process: [
      { step: '01', title: 'Data Deep-Dive', desc: 'We audit your analytics, identify drop-off points, and map every conversion path.' },
      { step: '02', title: 'Behavior Analysis', desc: 'Heatmaps, session recordings, and user flow analysis reveal what numbers alone can\'t.' },
      { step: '03', title: 'Fix Sprint', desc: 'We implement the highest-impact fixes first — typically 5-10 changes that move the needle.' },
      { step: '04', title: 'Measure & Report', desc: 'Within 2-3 weeks, you get a full report showing revenue delta and conversion improvements.' },
    ],
  },
  {
    tier: 1,
    slug: 'landing-page',
    name: 'Landing Page Revenue Engine',
    outcome: 'Turn your ad spend into booked calls.',
    price: '$4,000–7,000',
    timeline: 'Live in 1–2 weeks',
    heroSubtitle: 'Stop burning ad budget on pages that don\'t convert. We build landing pages engineered for one thing: revenue.',
    description: 'You\'re spending money on ads. The clicks are coming. But when visitors land on your page, something breaks. The headline doesn\'t resonate, the CTA is buried, the trust signals are missing. Our Landing Page Revenue Engine is built from conversion psychology — every element earns its place.',
    features: [
      'Conversion-focused copywriting',
      'Behavioral UX design principles',
      'A/B testing framework built-in',
      'Speed-optimized (sub-2s load)',
      'Analytics & tracking setup',
      'Mobile-first responsive design',
    ],
    results: [
      { metric: '3.2x', label: 'Average conversion lift' },
      { metric: '-62%', label: 'Cost per acquisition reduction' },
      { metric: '10 days', label: 'Average delivery time' },
    ],
    process: [
      { step: '01', title: 'Strategy', desc: 'We analyze your offer, audience, and competitive landscape.' },
      { step: '02', title: 'Copy & Design', desc: 'Conversion-focused copy paired with psychology-driven layout.' },
      { step: '03', title: 'Build & Test', desc: 'Pixel-perfect development with built-in A/B testing.' },
      { step: '04', title: 'Launch & Optimize', desc: 'Go live, measure, and iterate for maximum ROI.' },
    ],
  },
  {
    tier: 1,
    slug: 'site-speed',
    name: 'Site Speed & Core Web Vitals Fix',
    outcome: 'Google will start sending you more traffic.',
    price: '$2,500–4,500',
    timeline: 'Fixed in 1 week',
    heroSubtitle: 'A slow website isn\'t just frustrating — it\'s invisible. Google penalizes you, visitors bounce, and revenue evaporates.',
    description: 'Google has made Core Web Vitals a ranking signal. If your site is slow, you\'re being actively penalized. Every 100ms of load time costs you conversions. We diagnose and fix every performance bottleneck — from image optimization to server response times to JavaScript bloat.',
    features: [
      'Core Web Vitals audit & fix',
      'Image optimization & lazy loading',
      'JavaScript bundle analysis',
      'Server response time optimization',
      'CDN configuration',
      'Performance monitoring setup',
    ],
    results: [
      { metric: '97+', label: 'Average Lighthouse score achieved' },
      { metric: '+40%', label: 'Organic traffic increase' },
      { metric: '< 1s', label: 'Target load time' },
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Full Lighthouse audit, waterfall analysis, bundle review.' },
      { step: '02', title: 'Prioritize', desc: 'Rank fixes by impact — the 20% that drives 80% improvement.' },
      { step: '03', title: 'Implement', desc: 'Rapid-fire fixes deployed within days.' },
      { step: '04', title: 'Verify', desc: 'Before/after metrics proving measurable improvement.' },
    ],
  },
  {
    tier: 1,
    slug: 'authority-redesign',
    name: 'Authority Redesign Package',
    outcome: 'Stop losing clients to a website that looks like 2019.',
    price: '$6,000–12,000',
    timeline: 'Delivered in 3–4 weeks',
    heroSubtitle: 'Your website is your most important salesperson. If it looks dated, prospects assume your service quality matches.',
    description: 'First impressions are made in 50 milliseconds. If your website looks like it was built in 2019, you\'re losing deals before you even get a chance to pitch. Our Authority Redesign doesn\'t just make your site look modern — it rebuilds it as a conversion machine that communicates expertise, trust, and premium quality.',
    features: [
      'Complete visual identity refresh',
      'Conversion-optimized page structure',
      'Premium typography & design system',
      'Mobile-first responsive build',
      'SEO-optimized architecture',
      'Content strategy & copywriting',
    ],
    results: [
      { metric: '+144%', label: 'Average close rate increase' },
      { metric: '3 weeks', label: 'Average delivery time' },
      { metric: '50ms', label: 'First impression made' },
    ],
    process: [
      { step: '01', title: 'Discovery', desc: 'Brand audit, competitor analysis, audience research.' },
      { step: '02', title: 'Design', desc: 'High-fidelity designs that communicate authority.' },
      { step: '03', title: 'Develop', desc: 'Pixel-perfect build with performance baked in.' },
      { step: '04', title: 'Launch', desc: 'Deployment, monitoring, and post-launch optimization.' },
    ],
  },
  // Tier 2 — Growth Engine
  {
    tier: 2,
    tierLabel: 'TIER 02 — GROWTH ENGINE',
    tierHeadline: 'Where BIGWEB becomes your competitive advantage.',
    tierDescription: 'Ongoing partnerships that generate consistent, compounding returns. This is where the relationship deepens and results compound month over month.',
    slug: 'cro-retainer',
    name: 'CRO Retainer Program',
    outcome: 'Every month: more conversions from the same traffic.',
    price: '$3,000–6,000/mo',
    timeline: 'Ongoing optimization',
    heroSubtitle: 'The conversion work never stops. Every month, we find new leaks, test new hypotheses, and squeeze more revenue from your existing traffic.',
    description: 'A single conversion audit is a snapshot. A CRO retainer is a compounding investment. Every month, we analyze your latest data, identify new optimization opportunities, run A/B tests, and implement winning variations. The result? Your conversion rate climbs month after month — from the same traffic you\'re already paying for.',
    features: [
      'Monthly conversion analysis',
      'Continuous A/B testing program',
      'Behavioral analytics monitoring',
      'Landing page optimization',
      'Funnel refinement',
      'Monthly performance reports',
    ],
    results: [
      { metric: '+34%', label: 'Average monthly conversion growth' },
      { metric: '8.2x', label: 'Average ROI on retainer cost' },
      { metric: '14 mo', label: 'Average client engagement' },
    ],
    process: [
      { step: '01', title: 'Baseline', desc: 'Establish conversion benchmarks across all funnels.' },
      { step: '02', title: 'Test', desc: 'Monthly testing calendar with prioritized hypotheses.' },
      { step: '03', title: 'Implement', desc: 'Roll out winning variations, retire losers.' },
      { step: '04', title: 'Report', desc: 'Monthly report with revenue impact metrics.' },
    ],
  },
  {
    tier: 2,
    slug: 'ai-sales-agent',
    name: 'AI Sales Agent Build',
    outcome: 'A salesperson that works 24/7 and never calls in sick.',
    price: '$5,000–10,000 + retainer',
    timeline: 'Deployed in 3–5 weeks',
    heroSubtitle: 'While you sleep, your AI agent qualifies leads, answers objections, and books calls. Every hour of every day.',
    description: 'The AI sales revolution isn\'t coming — it\'s here. Our custom AI Sales Agents are trained on your business, your products, your objections, and your ideal customer profile. They don\'t just chat — they qualify, persuade, and convert. 24/7, at a fraction of the cost of a human salesperson.',
    features: [
      'Custom-trained on your business data',
      'Lead qualification logic',
      'Objection handling framework',
      'Calendar integration for booking',
      'CRM integration',
      'Performance analytics dashboard',
    ],
    results: [
      { metric: '24/7', label: 'Availability' },
      { metric: '+68%', label: 'Lead qualification rate' },
      { metric: '-73%', label: 'Cost per qualified lead' },
    ],
    process: [
      { step: '01', title: 'Train', desc: 'Feed the agent your FAQs, objection scripts, and product data.' },
      { step: '02', title: 'Build', desc: 'Custom conversation flows, integration with your tools.' },
      { step: '03', title: 'Test', desc: 'Rigorous testing with real scenarios before deployment.' },
      { step: '04', title: 'Deploy & Optimize', desc: 'Launch, monitor conversations, and improve over time.' },
    ],
  },
  {
    tier: 2,
    slug: 'revenue-funnel',
    name: 'Revenue Funnel System',
    outcome: 'Engineer your entire digital sales process.',
    price: '$6,000–15,000',
    timeline: 'Built in 4–6 weeks',
    heroSubtitle: 'Most businesses have traffic. What they don\'t have is a system. We build the complete revenue engine that turns strangers into customers.',
    description: 'Traffic without a funnel is a leaky bucket. We design and build your complete digital revenue system — from first touch to closed deal. Landing pages, email sequences, retargeting, lead scoring, CRM workflows — every piece engineered to move prospects toward revenue.',
    features: [
      'Complete funnel architecture',
      'Landing page suite',
      'Email sequence design',
      'Lead scoring system',
      'CRM workflow setup',
      'Retargeting strategy',
    ],
    results: [
      { metric: '-74%', label: 'Cost per acquisition' },
      { metric: '3.8x', label: 'Pipeline value increase' },
      { metric: '5 weeks', label: 'Average build time' },
    ],
    process: [
      { step: '01', title: 'Map', desc: 'Map every touchpoint from first click to closed deal.' },
      { step: '02', title: 'Design', desc: 'Design each funnel stage for maximum conversion.' },
      { step: '03', title: 'Build', desc: 'Build every component — pages, emails, automations.' },
      { step: '04', title: 'Launch', desc: 'Deploy, measure, and optimize the complete system.' },
    ],
  },
  {
    tier: 2,
    slug: 'bi-dashboard',
    name: 'Business Intelligence Dashboard',
    outcome: 'Finally see exactly where your money comes from — and where it goes.',
    price: '$4,000–8,000 + $1.5K/mo',
    timeline: 'Live in 3–4 weeks',
    heroSubtitle: 'Stop guessing. Start knowing. A real-time dashboard that shows you every revenue stream, every cost center, every opportunity.',
    description: 'Most businesses make decisions based on gut feeling and spreadsheets that are always out of date. Our BI Dashboard connects to your real data sources and gives you a real-time view of what\'s working, what\'s not, and where the opportunities are.',
    features: [
      'Custom KPI dashboard design',
      'Real-time data integration',
      'Revenue attribution modeling',
      'Customer lifetime value tracking',
      'Automated reporting',
      'Mobile-responsive access',
    ],
    results: [
      { metric: '10x', label: 'Faster decision-making' },
      { metric: '+22%', label: 'Revenue from identified opportunities' },
      { metric: 'Real-time', label: 'Data freshness' },
    ],
    process: [
      { step: '01', title: 'Discover', desc: 'Identify your key metrics and data sources.' },
      { step: '02', title: 'Design', desc: 'Design dashboards that answer your critical questions.' },
      { step: '03', title: 'Connect', desc: 'Integrate your data sources for real-time flow.' },
      { step: '04', title: 'Deliver', desc: 'Deploy, train your team, and start optimizing.' },
    ],
  },
  // Tier 3 — Revenue Transformation
  {
    tier: 3,
    tierLabel: 'TIER 03 — REVENUE TRANSFORMATION',
    tierHeadline: 'We become part of your leadership team.',
    tierDescription: 'High-ticket, deeply strategic engagements where BIGWEB operates as a true digital revenue partner. Not a vendor. Not a contractor. A partner with skin in the game.',
    slug: 'digital-revenue-transformation',
    name: 'Digital Revenue Transformation',
    outcome: 'A full-scale overhaul of your digital revenue engine.',
    price: '$20,000–50,000',
    timeline: '8–16 week engagement',
    heroSubtitle: 'When incremental improvements aren\'t enough. A complete reimagining of how your business generates revenue digitally.',
    description: 'Some businesses don\'t need a tweak. They need a transformation. Our Digital Revenue Transformation is a comprehensive, multi-month engagement that redesigns every digital touchpoint for maximum revenue generation. Strategy, design, development, automation, and ongoing optimization — all under one roof.',
    features: [
      'Complete digital strategy overhaul',
      'Full website redesign & rebuild',
      'Revenue funnel architecture',
      'AI & automation integration',
      'Team training & enablement',
      'Ongoing performance optimization',
    ],
    results: [
      { metric: '+250%', label: 'Average revenue increase' },
      { metric: '12 weeks', label: 'Average engagement duration' },
      { metric: '$140K+', label: 'Average client annual revenue lift' },
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Complete digital presence audit and opportunity analysis.' },
      { step: '02', title: 'Strategy', desc: 'Revenue transformation roadmap with clear milestones.' },
      { step: '03', title: 'Execute', desc: 'Phased implementation with weekly check-ins.' },
      { step: '04', title: 'Scale', desc: 'Ongoing optimization and growth compounding.' },
    ],
  },
  {
    tier: 3,
    slug: 'saas-mvp',
    name: 'SaaS MVP Build',
    outcome: 'Turn your industry problem into your competitive product.',
    price: '$15,000–40,000',
    timeline: '6–12 week build',
    heroSubtitle: 'You know your industry\'s pain points better than anyone. We turn that knowledge into a software product.',
    description: 'You\'ve identified a problem your industry faces. You have the domain expertise. What you need is a team that can turn that vision into a working, revenue-generating SaaS product — fast. We build MVPs that are market-ready, not just demo-ready.',
    features: [
      'Product strategy & scoping',
      'UX/UI design system',
      'Full-stack development',
      'Payment & subscription integration',
      'User analytics & onboarding',
      'Launch strategy & support',
    ],
    results: [
      { metric: '8 weeks', label: 'Average time to market' },
      { metric: '92%', label: 'MVP-to-revenue conversion' },
      { metric: '$2.4M', label: 'Total client MRR generated' },
    ],
    process: [
      { step: '01', title: 'Scope', desc: 'Define core features, user flows, and success metrics.' },
      { step: '02', title: 'Design', desc: 'Complete design system and interactive prototype.' },
      { step: '03', title: 'Build', desc: 'Sprint-based development with weekly demos.' },
      { step: '04', title: 'Launch', desc: 'Market-ready deployment with analytics baked in.' },
    ],
  },
  {
    tier: 3,
    slug: 'ai-ops',
    name: 'AI Ops Integration',
    outcome: 'Automate the operations that are slowing you down.',
    price: '$8,000–20,000 + ongoing',
    timeline: '4–8 weeks',
    heroSubtitle: 'Your team is spending hours on tasks that AI can do in seconds. We identify and automate them.',
    description: 'Proposals. Follow-ups. Reporting. Data entry. Scheduling. Your team is drowning in operational work that doesn\'t generate revenue. Our AI Ops Integration identifies the highest-impact automation opportunities and builds custom AI workflows that free your team to focus on growth.',
    features: [
      'Operations audit & opportunity mapping',
      'Custom AI workflow design',
      'Integration with existing tools',
      'Team training & adoption support',
      'ROI tracking & reporting',
      'Ongoing optimization & expansion',
    ],
    results: [
      { metric: '40hrs/wk', label: 'Average time saved per team' },
      { metric: '-60%', label: 'Operational cost reduction' },
      { metric: '3 weeks', label: 'Time to first automation live' },
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Map every manual process and score by automation potential.' },
      { step: '02', title: 'Design', desc: 'Design AI workflows for the highest-impact opportunities.' },
      { step: '03', title: 'Build', desc: 'Develop, test, and integrate automations.' },
      { step: '04', title: 'Train', desc: 'Onboard your team and monitor adoption.' },
    ],
  },
  {
    tier: 3,
    slug: 'fractional-cto',
    name: 'Fractional CTO / Digital Partner',
    outcome: 'Executive-level digital leadership at a fraction of the full-time cost.',
    price: '$5,000–12,000/mo',
    timeline: 'Ongoing',
    heroSubtitle: 'You need strategic digital leadership, but you don\'t need (or can\'t afford) a full-time CTO. We fill that gap.',
    description: 'Every growing business reaches a point where digital decisions become too important to make without senior technical leadership. Our Fractional CTO service gives you access to seasoned digital executives who integrate with your leadership team, guide technology decisions, manage vendor relationships, and ensure your digital investments generate returns.',
    features: [
      'Weekly strategic advisory sessions',
      'Technology roadmap development',
      'Vendor management & evaluation',
      'Team hiring & mentoring',
      'Architecture & security review',
      'Board-ready reporting',
    ],
    results: [
      { metric: '60%', label: 'Cost savings vs full-time CTO' },
      { metric: '+180%', label: 'Average digital ROI improvement' },
      { metric: '18 mo', label: 'Average engagement length' },
    ],
    process: [
      { step: '01', title: 'Assess', desc: 'Evaluate current digital maturity and gaps.' },
      { step: '02', title: 'Integrate', desc: 'Embed with your leadership team and roadmap priorities.' },
      { step: '03', title: 'Execute', desc: 'Drive initiatives, manage vendors, ship outcomes.' },
      { step: '04', title: 'Scale', desc: 'Build internal capabilities and phase out as needed.' },
    ],
  },
];

export const CASE_STUDIES = [
  {
    index: '01',
    slug: 'ecommerce-conversion-turnaround',
    client: 'E-Commerce Brand',
    location: 'Lagos, Nigeria',
    tags: ['Conversion Audit', 'Landing Page', 'Site Speed'],
    problem: '5,200 monthly visitors. $8,000/month in revenue. The traffic was there. The conversions weren\'t.',
    delivered: 'Full-funnel conversion audit, landing page overhaul with behavioral psychology principles, and a site speed fix that brought load time under 1.5 seconds.',
    result: 'Revenue grew from $8,000 to $31,000/month in 90 days — without increasing ad spend.',
    metric: '+288%',
    metricLabel: 'Revenue Growth',
    timeline: '90 days',
    bg: 'var(--color-bg-secondary)',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    fullContent: 'When this Lagos-based e-commerce brand approached us, they were ready to fire their ad agency. They were driving over 5,000 visitors a month, but cart abandonment was sitting at a staggering 82%. We deployed our Conversion Audit and discovered that their mobile checkout flow required 14 taps to complete a purchase, and their product pages lacked crucial trust signals. We redesigned the entire mobile funnel, reduced the checkout to 3 steps, and implemented a one-click upsell system. The result was immediate.'
  },
  {
    index: '02',
    slug: 'professional-services-authority',
    client: 'Professional Services Firm',
    location: 'Abuja, Nigeria',
    tags: ['Authority Redesign', 'AI Sales Agent'],
    problem: 'Premium service. Amateur website. They were losing pitches to inferior competitors whose websites looked more credible.',
    delivered: 'Complete authority redesign positioning them as the obvious premium choice, paired with an AI Sales Agent that qualifies leads 24/7.',
    result: 'Close rate increased from 18% to 44% within 60 days. The site now does the selling.',
    metric: '+144%',
    metricLabel: 'Close Rate Increase',
    timeline: '60 days',
    bg: 'var(--color-bg-primary)',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    fullContent: 'This Abuja firm charged premium retainers but had a website built on a $50 template from 2018. When prospects researched them after a pitch, the visual disconnect killed the deal. We stripped everything back and built an "Enterprise Minimalist" digital presence that matched their real-world authority. We then integrated a custom AI Sales Agent trained on their methodology to answer complex client questions 24/7 and book qualification calls automatically.'
  },
  {
    index: '03',
    slug: 'saas-funnel-optimization',
    client: 'B2B SaaS Startup',
    location: 'Remote',
    tags: ['Revenue Funnel', 'CRO Retainer'],
    problem: 'Running paid ads at $12,000/month. Cost per acquisition at $340. The funnel was leaking at every stage.',
    delivered: 'Complete revenue funnel rebuild with lead scoring, email nurture sequences, and a CRO retainer to continuously optimize every touchpoint.',
    result: 'CAC dropped from $340 to $89. Pipeline value tripled. Ad spend reduced by 30%.',
    metric: '−74%',
    metricLabel: 'Cost Per Acquisition',
    timeline: '5 months',
    bg: 'var(--color-bg-secondary)',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    fullContent: 'This remote B2B SaaS startup had an incredible product but a broken go-to-market funnel. They were paying for clicks but failing to capture intent. We mapped their entire customer journey and identified a massive drop-off between the ad click and the trial sign-up. We rebuilt their landing pages to focus purely on the "Aha!" moment of their software, built an automated email nurture sequence for abandoned trials, and implemented dynamic lead scoring for their sales team.'
  },
];

export const getCaseStudyBySlug = (slug: string) => CASE_STUDIES.find(cs => cs.slug === slug);

export const TESTIMONIALS = [
  {
    quote: "BIGWEB didn't just redesign our site — they redesigned our revenue. The numbers speak for themselves.",
    name: 'Adaeze O.',
    role: 'CEO',
    company: 'E-commerce Brand',
    initials: 'AO',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1b4393?auto=format&fit=crop&w=150&q=80',
  },
  {
    quote: "We went from losing pitches to winning them. The authority redesign paid for itself in the first month.",
    name: 'Chukwuma E.',
    role: 'Managing Partner',
    company: 'Professional Services',
    initials: 'CE',
    avatar: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&w=150&q=80',
  },
  {
    quote: "The AI sales agent is the best investment we've made. It books more calls than our human team ever did.",
    name: 'Sarah K.',
    role: 'Founder',
    company: 'B2B SaaS',
    initials: 'SK',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
  },
];

export const ARTICLES = [
  {
    slug: 'why-websites-fail-to-convert',
    category: 'CONVERSION',
    title: 'Why 94% of websites with traffic still fail to convert — and the 3 fixes that work.',
    excerpt: 'You have the visitors. Your analytics prove it. But somewhere between the first click and the final conversion, money is leaking out of your funnel.',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'ai-sales-agent-underpriced',
    category: 'AI',
    title: "The AI sales agent is the most underpriced tool available to SMBs right now.",
    excerpt: "While enterprise companies invest millions in AI infrastructure, a $5,000 AI agent can outperform a $60,000/year salesperson. Here's why.",
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'upsell-ladder-case-study',
    category: 'STRATEGY',
    title: "The $4,000 project that became a $6,000/month partnership — how BIGWEB's upsell ladder works.",
    excerpt: "Every engagement we design delivers standalone value — and makes the next step obvious. Our clients don't feel upsold. They feel guided.",
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
  },
];

export const FULL_ARTICLES = [
  ...ARTICLES,
  {
    slug: 'core-web-vitals-revenue',
    category: 'PERFORMANCE',
    title: "Your Core Web Vitals score is costing you customers — here's the math.",
    excerpt: "Google doesn't just use Core Web Vitals for ranking. Slow sites lose 53% of mobile visitors. We break down the revenue impact per second of load time.",
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'agency-model-broken',
    category: 'INDUSTRY',
    title: "The traditional agency model is broken. Here's what replaces it.",
    excerpt: 'Open-ended retainers, vague deliverables, and vanity metrics. The old model served agencies, not clients. The new model is structured, measured, and accountable.',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    slug: 'redesign-roi',
    category: 'DESIGN',
    title: "How to calculate the actual ROI of a website redesign (most agencies can't).",
    excerpt: "A redesign isn't an expense — it's an investment. But only if you can measure the return. Here's the framework we use with every client.",
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
  },
];

export function getServiceBySlug(slug: string) {
  return SERVICES.find(s => s.slug === slug);
}

export function getServicesByTier(tier: number) {
  return SERVICES.filter(s => s.tier === tier);
}
