
'use client'

import Navigation from '@/components/AdvancedNavigation'
import Footer from '@/components/Footer'
import HeroPremium from '@/components/services/HeroPremium'
import BentoGrid from '@/components/services/BentoGrid'
import ProcessTimeline from '@/components/services/ProcessTimeline'
import Breadcrumbs from '@/components/seo/Breadcrumbs'
import { ServiceSchema, FAQSchema, BreadcrumbSchema } from '@/components/seo/JsonLd'
import { Bot, BrainCircuit, Sparkles, Search, MessageSquare, Database, Cpu, Network } from 'lucide-react'
import { motion } from 'framer-motion'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { ArrowRight, LineChart } from 'lucide-react'
import RelatedServices from "@/components/services/RelatedServices"

const features = [
    {
        title: 'LLM Answer Optimization',
        description: 'Optimize your content to be cited as the primary source by ChatGPT, Claude, Gemini, and Perplexity.',
        icon: Bot,
        colSpan: 2 as const,
        rowSpan: 2 as const,
        bgImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=90'
    },
    {
        title: 'Structured Data for AI',
        description: 'Implement advanced schema markup that helps AI models understand the semantic relationships in your data.',
        icon: Database,
        colSpan: 1 as const
    },
    {
        title: 'Entity Authority Building',
        description: 'Establish your brand as a recognized "Entity" in the Knowledge Graph, ensuring AI models trust your facts.',
        icon: BrainCircuit,
        colSpan: 1 as const
    },
    {
        title: 'Conversational Content',
        description: 'Restructure content into Q&A formats that mirror natural language queries used in voice and AI search.',
        icon: MessageSquare,
        colSpan: 1 as const
    },
    {
        title: 'Zero-Click Optimization',
        description: 'Win the "Featured Snippet" and AI overview slots to capture traffic without requiring a click.',
        icon: Search,
        colSpan: 1 as const
    },
    {
        title: 'AI Performance Tracking',
        description: 'Monitor your brand\'s visibility and sentiment across major Large Language Models.',
        icon: LineChart,
        colSpan: 2 as const
    }
]



const processSteps = [
    {
        number: '01',
        title: 'AI Visibility Audit',
        description: 'We analyze how your brand currently appears in ChatGPT, Gemini, and Perplexity. We identify hallucinations, missing data, and citation gaps compared to competitors.',
        tags: ['LLM Audit', 'Hallucination Check', 'Citation Analysis']
    },
    {
        number: '02',
        title: 'Entity Optimization',
        description: 'We restructure your digital footprint to define your brand as a clear "Entity". This involves updating Knowledge Graphs, Wikidata, and ensuring consistent NAP (Name, Address, Phone) + Facts across the web.',
        tags: ['Knowledge Graph', 'Wikidata', 'Entity Linking']
    },
    {
        number: '03',
        title: 'Content Re-Engineering',
        description: 'We rewrite key content into "AI-digestible" formats. This means direct answers, bullet points, data tables, and semantic HTML that makes it easy for bots to extract facts.',
        tags: ['Semantic HTML', 'Direct Answers', 'Data Tables']
    },
    {
        number: '04',
        title: 'Technical Schema Implementation',
        description: 'We deploy advanced JSON-LD schema (FAQ, HowTo, Article, Organization) to explicitly tell AI models what your content means, reducing ambiguity.',
        tags: ['JSON-LD', 'Schema.org', 'Structured Data']
    },
    {
        number: '05',
        title: 'Citation Building',
        description: 'We secure mentions and backlinks from high-authority sources that are already in the training data of major LLMs, increasing the likelihood of your brand being cited.',
        tags: ['Digital PR', 'Authority Building', 'Training Data']
    }
]

const faqs = [
    {
        question: 'What is GAIO (Generative AI Optimization)?',
        answer: 'GAIO is the process of optimizing your online presence to ensure your brand is visible, accurate, and cited by Generative AI models like ChatGPT, Gemini, and Claude. Unlike SEO, which targets search engines, GAIO targets the "Answer Engines" that are replacing traditional search.'
    },
    {
        question: 'How is GAIO different from SEO?',
        answer: 'SEO focuses on ranking links on a search results page (SERP). GAIO focuses on being the direct answer generated by an AI. SEO metrics are clicks and rankings; GAIO metrics are citations, sentiment, and "Share of Voice" in AI responses.'
    },
    {
        question: 'Why do I need GAIO now?',
        answer: 'Search behavior is shifting. Gartner predicts organic search traffic will drop by 50% by 2028 as users switch to AI assistants. If you aren\'t optimized for AI, you will disappear from the primary way people find information.'
    },
    {
        question: 'Can you guarantee my brand will appear in ChatGPT?',
        answer: 'We cannot "force" an LLM to say something, as they are non-deterministic. However, by establishing high Entity Authority and structuring data correctly, we significantly increase the probability of your brand being cited as the factual source for relevant queries.'
    },
    {
        question: 'Is GAIO a replacement for SEO?',
        answer: 'Not yet. It is a complementary strategy. Traditional search (Google) is still dominant, but AI Search (SGE) is growing fast. A robust strategy requires both: SEO for today\'s traffic, and GAIO for tomorrow\'s visibility.'
    }
]

const breadcrumbItems = [
    { label: 'Services', href: '/services' },
    { label: 'GAIO (AI Optimization)', href: '/services/gaio' }
]

export default function GAIOPage() {
    return (
        <main className="min-h-screen bg-background selection:bg-purple-500/30">
            {/* Structured Data */}
            <ServiceSchema
                name="Generative AI Optimization (GAIO)"
                description="Optimize your brand for ChatGPT, Gemini, and AI Search. The future of SEO is Answer Engine Optimization."
                serviceType="AI Optimization"
                ratingValue={5.0}
                reviewCount={42}
            />
            <FAQSchema faqs={faqs} />
            <BreadcrumbSchema items={[
                { name: 'Home', url: 'https://bigwebdigital.com' },
                ...breadcrumbItems.map(item => ({ name: item.label, url: `https://bigwebdigital.com${item.href}` }))
            ]} />

            <Navigation />

            <div className="container mx-auto px-6">
                <Breadcrumbs items={breadcrumbItems} />
            </div>

            <HeroPremium
                title="The Future of SEO is"
                highlight="Generative AI"
                description="Don't just rank on Google. Be the answer on ChatGPT, Gemini, and Perplexity. We optimize your brand for the AI era."
                themeColor="purple"
            />

            {/* Introduction Section */}
            <section className="py-24 px-6">
                <div className="container mx-auto max-w-4xl">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                    >
                        <h2 className="text-4xl font-bold mb-6">From Search Engines to Answer Engines</h2>
                        <div className="prose prose-lg dark:prose-invert max-w-none">
                            <blockquote className="llm-quotable border-l-4 border-purple-500 bg-purple-500/5 p-6 rounded-r-lg not-italic mb-8">
                                <p className="text-xl font-medium text-foreground m-0">
                                    "By 2028, brand organic search traffic will decrease by 50% or more as consumers embrace generative AI-powered search."
                                    <span className="block text-sm text-muted-foreground mt-2">— Gartner Research</span>
                                </p>
                            </blockquote>

                            <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                                The way people find information has changed forever. Instead of typing keywords into Google and clicking ten blue links,
                                users are asking complex questions to AI assistants like <strong>ChatGPT, Claude, and Gemini</strong>.
                            </p>
                            <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                                If your brand isn't optimized for these Large Language Models (LLMs), you aren't just losing rankings—you're becoming invisible.
                                <strong>GAIO (Generative AI Optimization)</strong> is the new discipline of ensuring your business is the primary source of truth
                                for AI models.
                            </p>
                        </div>
                    </motion.div>
                </div>
            </section>

            <BentoGrid
                title="GAIO Capabilities"
                subtitle="A comprehensive suite of services designed to make your brand 'AI-Readable'."
                items={features}
                themeColor="purple"
            />

            <ProcessTimeline
                steps={processSteps}
                themeColor="purple"
            />

            {/* FAQ Section */}
            <section className="py-32 px-6">
                <div className="container mx-auto max-w-4xl">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-center mb-16"
                    >
                        <h2 className="text-4xl md:text-5xl font-bold mb-4">Frequently Asked Questions</h2>
                        <p className="text-xl text-muted-foreground">
                            Understanding the shift to AI Search
                        </p>
                    </motion.div>

                    <div className="space-y-4">
                        {faqs.map((faq, index) => (
                            <motion.details
                                key={index}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: index * 0.05 }}
                                className="group bg-card border border-border rounded-xl overflow-hidden hover:border-purple-500/50 transition-colors"
                            >
                                <summary className="p-6 cursor-pointer list-none font-bold text-lg flex items-center justify-between">
                                    <span>{faq.question}</span>
                                    <svg className="w-5 h-5 transition-transform group-open:rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                                    </svg>
                                </summary>
                                <div className="px-6 pb-6 pt-0 text-muted-foreground">
                                    {faq.answer}
                                </div>
                            </motion.details>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="py-32 px-6 relative overflow-hidden">
                <div className="absolute inset-0 bg-purple-500/5" />
                <div className="container mx-auto max-w-4xl text-center relative z-10">
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                    >
                        <Sparkles className="w-16 h-16 mx-auto mb-6 text-purple-500" />
                        <h2 className="text-5xl md:text-7xl font-bold mb-8 tracking-tight">
                            Future-Proof Your Brand
                        </h2>
                        <p className="text-xl text-muted-foreground mb-12 max-w-2xl mx-auto">
                            Get a comprehensive AI Visibility Audit and find out what ChatGPT is saying about you.
                        </p>
                        <div className="flex flex-wrap gap-4 justify-center">
                            <Link href="/audit">
                                <Button size="lg" className="h-16 px-10 text-xl rounded-full bg-purple-600 hover:bg-purple-700 text-white shadow-xl shadow-purple-500/20">
                                    Get AI Audit
                                    <ArrowRight className="ml-2 w-6 h-6" />
                                </Button>
                            </Link>
                            <Link href="/contact">
                                <Button size="lg" variant="outline" className="h-16 px-10 text-xl rounded-full">
                                    Consult an Expert
                                </Button>
                            </Link>
                        </div>
                    </motion.div>
                </div>
            </section>

            <RelatedServices currentPath="/services/gaio" />

            <Footer />
        </main>
    )
}
